!
frr version 8.4.1_git
frr defaults traditional
hostname RT-03
no ipv6 forwarding
!
interface eth1
 ip address 10.0.255.2/24
exit
!
interface eth2
 ip address 10.70.10.254/24
exit
!
interface lo
 ip address 3.3.3.3/32
exit
!
router bgp 65020
 bgp router-id 3.3.3.3
 neighbor AS65010 peer-group
 neighbor AS65010 remote-as external
 neighbor 10.0.255.1 peer-group AS65010
 !
 address-family ipv4 unicast
  network 10.70.10.0/24
 exit-address-family
exit
!
end
