! Command: show running-config
! device: RT-01 (cEOSLab, EOS-4.31.5M-38783123.4315M (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$3w/xZtoH2473QhVz$cqQc5Dn688uYQmu23TlQptMUHOm5c9jWYGyVZIndZBeMjLctM1ieT5U7IVzAbaJDEi2Lv/FblkK6OJ26xmP90/
username user privilege 0 role USER secret sha512 $6$xwMn76hPsPWdeYU6$AhYdBSgfx/umjdOU6WNMKe/EruDSX1RUzYeoPUwc72WJM1D3I0retAx/XWYZeQGXVKd4yZQNog2882B0U1h5s.
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname RT-01
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api http-commands
   no shutdown
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
aaa authorization commands all default local
!
interface Ethernet1
   no switchport
   ip address 172.16.10.254/24
!
interface Ethernet2
   mtu 2011
   no switchport
   ip address 10.0.1.1/30
   ip ospf cost 10
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
interface Loopback0
   ip address 1.1.1.1/32
   ip ospf cost 1
   ip ospf area 0.0.0.0
!
interface Management0
   ip address 172.20.20.5/24
   ipv6 address 3fff:172:20:20::5/64
!
ip routing
!
role USER
   10 permit command ^show.*
   20 deny command .*
!
router bgp 65010
   router-id 1.1.1.1
   neighbor AS65010 peer group
   neighbor AS65010 remote-as 65010
   neighbor AS65010 update-source Loopback0
   neighbor 2.2.2.2 peer group AS65010
   network 172.16.10.0/24
!
router ospf 1
   router-id 1.1.1.1
   max-lsa 12000
!
end
