!
hostname RT-02
username clab
 group root-lr
 group cisco-support
 secret 10 $6$plYQh0A7Lfmp8h0.$L4OPEzBIPeUkIXRFH1j1MesUDmlNirYizka4sPa55BJj48poPPY3kxk.CsChx6DCHC83buomdeva7nSmyH58a1
!
grpc
 port 9339
 no-tls
 address-family dual
!
line default
 transport input ssh
!
netconf-yang agent
 ssh
!
interface Loopback0
 ipv4 address 2.2.2.2 255.255.255.255
!
interface MgmtEth0/RP0/CPU0/0
!
interface GigabitEthernet0/0/0/1
 ipv4 address 10.0.1.2 255.255.255.252
!
interface GigabitEthernet0/0/0/2
 ipv4 address 10.0.255.1 255.255.255.0
!
prefix-set AS65010
  172.16.10.0/24
end-set
!
prefix-set AS65020
  10.70.10.0/24
end-set
!
route-policy AS65020-IN
  if destination in AS65020 then
    pass
  else
    drop
  endif
end-policy
!
route-policy AS65010-OUT
  if destination in AS65020 then
    pass
  else
    drop
  endif
end-policy
!
route-policy AS65020-OUT
  if destination in AS65010 then
    pass
  else
    drop
  endif
end-policy
!
router static
 address-family ipv4 unicast
  0.0.0.0/0 MgmtEth0/RP0/CPU0/0 172.20.20.1
 !
 address-family ipv6 unicast
  ::/0 MgmtEth0/RP0/CPU0/0 3fff:172:20:20::1
 !
!
router ospf 1
 router-id 2.2.2.2
 area 0
  interface Loopback0
   cost 1
  !
  interface GigabitEthernet0/0/0/1
   cost 10
   network point-to-point
  !
 !
!
router bgp 65010
 bgp router-id 2.2.2.2
 address-family ipv4 unicast
 !
 neighbor-group AS65010
  remote-as 65010
  update-source Loopback0
  address-family ipv4 unicast
   next-hop-self
   route-policy AS65010-OUT out
  !
 !
 neighbor-group AS65020
  remote-as 65020
  address-family ipv4 unicast
   route-policy AS65020-IN in
   route-policy AS65020-OUT out
  !
 !
 neighbor 1.1.1.1
  use neighbor-group AS65010
 !
 neighbor 10.0.255.2
  use neighbor-group AS65020
 !
!
ssh server v2
ssh server netconf vrf default
end
