! Command: show running-config
! device: RT-S-02 (cEOSLab, EOS-4.34.1F-42424637.4341F (engineering build))
!
no aaa root
!
no service interface inactive port-id allocation disabled
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname RT-S-02
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
interface Port-Channel1
   no switchport
   ipv6 enable
!
interface Port-Channel2
   no switchport
   ipv6 enable
!
interface Ethernet1
   no switchport
   ipv6 enable
!
interface Ethernet2
   no switchport
   ipv6 enable
!
interface Ethernet3
   no switchport
   ipv6 enable
!
interface Ethernet4
   no switchport
   ipv6 enable
!
interface Ethernet5
   no switchport
   ipv6 enable
   channel-group 1 mode active
!
interface Ethernet6
   no switchport
   ipv6 enable
   channel-group 2 mode active
!
interface Loopback0
   ip address 10.1.254.12/32
!
interface Management0
   ip address 172.20.20.11/24
   ipv6 address 3fff:172:20:20::b/64
!
ip routing ipv6 interfaces
!
ip prefix-list PREFIX_LOOPBACK seq 5 permit 10.1.254.0/24 ge 32
!
ipv6 unicast-routing
!
route-map ACCEPT_PREFIX_LOOPBACK permit 10
   match ip address prefix-list PREFIX_LOOPBACK
!
peer-filter ALLOW-ASN
   10 match as-range 65000-65199 result accept
!
router bgp 65110
   router-id 10.1.254.12
   no bgp default ipv4-unicast
   bgp default ipv4-unicast transport ipv6
   bgp listen range 10.1.254.0/24 peer-group EVPN peer-filter ALLOW-ASN
   neighbor EVPN peer group
   neighbor EVPN update-source Loopback0
   neighbor EVPN ebgp-multihop 3
   neighbor EVPN send-community
   neighbor GW peer group
   neighbor GW bfd
   neighbor LEAF peer group
   neighbor LEAF bfd
   neighbor 10.1.254.21 peer group EVPN
   neighbor 10.1.254.22 peer group EVPN
   neighbor 10.1.254.23 peer group EVPN
   neighbor 10.1.254.24 peer group EVPN
   neighbor 10.1.254.31 peer group EVPN
   neighbor 10.1.254.32 peer group EVPN
   neighbor interface Et1-4 peer-group LEAF peer-filter ALLOW-ASN
   neighbor interface Po1-2 peer-group GW peer-filter ALLOW-ASN
   !
   address-family evpn
      neighbor EVPN activate
      neighbor EVPN next-hop-unchanged
   !
   address-family ipv4
      neighbor GW activate
      neighbor GW route-map ACCEPT_PREFIX_LOOPBACK in
      neighbor GW route-map ACCEPT_PREFIX_LOOPBACK out
      neighbor GW next-hop address-family ipv6 originate
      neighbor LEAF activate
      neighbor LEAF route-map ACCEPT_PREFIX_LOOPBACK in
      neighbor LEAF route-map ACCEPT_PREFIX_LOOPBACK out
      neighbor LEAF next-hop address-family ipv6 originate
      network 10.1.254.12/32
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
end
