username: admin
timeout: 30s

# 共通サブスクリプション設定
common_arista_subscriptions: &common_arista_subs
  skip-verify: true
  insecure: true
  password: admin
  encoding: json_ietf
  subscriptions:
    - cpu
    - mem
    - interface_state
    - interface_config
    - bgp

common_srl_subscriptions: &common_srl_subs
  skip-verify: true
  insecure: false
  password: NokiaSrl1!
  encoding: json_ietf
  subscriptions:
    - cpu
    - mem
    - interface_state
    - interface_config
    - bgp

# ターゲットデバイス設定
targets:
  rt01:6030: *common_arista_subs
  rt02:6030: *common_arista_subs
  rt03:57400: *common_srl_subs

# サブスクリプションの詳細
subscriptions:

  ### General Information ###
  cpu:
    paths:
      - /components/component/cpu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  mem:
    paths:
      - /system/memory/state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  interface_state:
    paths:
      - /interfaces/interface/state/counters
      - /interfaces/interface/state/admin-status
      - /interfaces/interface/state/oper-status
      - /interfaces/interface/subinterfaces/subinterface/ipv4/state/mtu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  interface_config:
    paths:
      - /interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/config
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  bgp:
    paths:
      - /network-instances/network-instance[name=default]/protocols/protocol[name=BGP]/bgp/
    mode: stream
    stream-mode: samlpe
    sample-interval: 5s

# 出力設定
outputs:
  prom-output:
    type: prometheus
    listen: :9273
    append-subscription-name: true
    event-processors:
      - trim-prefixes
      - bounce-map
      - rename-interface
      - rename-source
      - eos-version

# プロセッサ設定
processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  bounce-map:
    event-strings:
      value-names:
        - oper-status
        - admin-status
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
        - replace:
            apply-on: "value"
            old: "UP"
            new: "1"
        - replace:
            apply-on: "value"
            old: "DOWN"
            new: "0"
  rename-interface:
    event-strings:
      tag-names:
        - "^interface_name"
      transforms:
        - replace:
            apply-on: "value"
            old: "ethernet-(\\d+)/(\\d+)"
            new: "e$1-$2"
        - replace:
            apply-on: "value"
            old: "Ethernet(\\d+)"
            new: "eth$1"
  rename-source:
    event-strings:
      tag-names:
        - "^source"
      transforms:
        - replace:
            apply-on: "value"
            old: "(\\d+):(\\d+)"
            new: "$1"
  eos-version:
    event-strings:
      value-names:
        - ".*version$"
        - ".*arch$"
      transforms:
        - replace:
            apply-on: "value"
            old: "EOS"
            new: "eos"
