! Command: show running-config
! device: rt05 (cEOSLab, EOS-4.31.5M-38783521.4315M (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$M7OWFlN87sji6kJ8$r3KtSneo0fpUOoZONgwXo6dOI16dKr3pFla3PRwk6Y044xjtRAY7ojtSFri4OyNjZMizzGisnsa2mAu1QIjs.1
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname rt05
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
clock timezone Asia/Tokyo
!
management api http-commands
   no shutdown
!
management api gnmi
   transport grpc default
   provider eos-native
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.0.1.37/30
   ip ospf cost 10
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
interface Ethernet2
   no switchport
   ip address 10.0.1.29/30
   ip ospf cost 10
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
interface Ethernet3
   no switchport
   ip address 192.168.30.254/24
!
interface Loopback0
   ip address 5.5.5.5/32
   ip ospf cost 1
   ip ospf area 0.0.0.0
!
interface Management0
   ip address 172.100.100.131/24
!
ip routing
!
ip route 0.0.0.0/0 172.20.20.1
!
ipv6 route ::/0 3fff:172:20:20::1
!
router ospf 1
   router-id 5.5.5.5
   network 5.5.5.5/32 area 0.0.0.0
   network 192.168.30.0/24 area 0.0.0.0
   max-lsa 12000
!
end