!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$YrlUFL6S4EsvtZa5$n.9bFK/pW1Ngj6SDkQ3fTxxRL/t/b1R8KbsdMrWrewkcTSJFM7pl5nydWM.U2yyYOs0JsTX3HvrAV.DToQKo01
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname rt02
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
clock timezone Asia/Tokyo
!
management api http-commands
   no shutdown
!
management api gnmi
   transport grpc default
      no shutdown
   provider eos-native
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   mtu 2000
   ip address 192.168.10.2/24
   ip ospf cost 10
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
interface Ethernet2
   no switchport
   mtu 2000
   ip address 10.0.10.1/24
!
interface Loopback0
   ip address 2.2.2.2/32
   ip ospf cost 1
   ip ospf area 0.0.0.0
!
interface Management0
!
ip routing
!
ip route 0.0.0.0/0 172.20.20.1
!
ipv6 route ::/0 3fff:172:20:20::1
!
router bgp 65010
   router-id 2.2.2.2
   neighbor eBGP peer group
   neighbor eBGP remote-as 65020
   neighbor iBGP peer group
   neighbor iBGP remote-as 65010
   neighbor iBGP update-source loopback 0
   neighbor 1.1.1.1. peer group iBGP
   neighbor 1.1.1.1 next-hop-self
   neighbor 10.0.10.2 peer group eBGP
!
router ospf 1
   router-id 2.2.2.2
   network 2.2.2.2/32 area 0.0.0.0
   max-lsa 12000
!
end