!
frr version 8.4.1_git
frr defaults datacenter
hostname SV-06
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 20.110.1.1/32
!
interface eth1
 ip address 192.168.22.223/26
exit
!
router bgp 65036
 bgp router-id 192.168.22.223
 no bgp default ipv4-unicast
 neighbor ToR peer-group
 neighbor ToR remote-as external
 neighbor 192.168.22.200 peer-group ToR
 !
 address-family ipv4 unicast
  redistribute connected route-map ADV_LO
  neighbor ToR activate
 exit-address-family
exit
!
route-map ADV_LO permit 10
 match interface lo
exit
!
end
