!
frr version 8.4.1_git
frr defaults datacenter
hostname SV-02
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 20.5.5.5/32
!
interface eth1
 ip address 192.168.11.112/26
exit
!
router bgp 65032
 bgp router-id 192.168.11.112
 no bgp default ipv4-unicast
 neighbor ToR peer-group
 neighbor ToR remote-as external
 neighbor 192.168.11.100 peer-group ToR
 !
 address-family ipv4 unicast
  redistribute connected route-map ADV_LO
  neighbor ToR activate
 exit-address-family
exit
!
route-map ADV_LO permit 10
 match interface lo
exit
!
route-map PERMIT_ALL permit 10
exit
!
end
