---
anchors: # 再利用可能な設定の定義
  thresholds-operstate: &thresholds-operstate # インターフェースの状態によって色を決定
  - color: red
    level: 0
  - color: green
    level: 1
  thresholds-traffic: &thresholds-traffic
  - color: gray
    level: 0
  - color: green
    level: 199999
  - color: yellow
    level: 500000
  - color: orange
    level: 1000000
  - color: red
    level: 5000000
  label-config: &label-config
    separator: replace
    units: bps
    decimalPoints: 1
    valueMappings:
    - valueMax: 199999
      text: ​
    - valueMin: 200000
cellIdPreamble: cell-
cells:
  sw01:eth1:pc01:eth1:
    dataRef: oper-state:sw01:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:sw01:eth1:pc01:eth1:
    dataRef: ping_loss_ratio:pc03:192.168.10.1
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  pc02:eth1:sw01:eth2:
    dataRef: oper-state:pc02:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:pc02:eth1:sw01:eth2:
    dataRef: sw01:eth2:in
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  pc03:eth1:rt01:eth2:
    dataRef: oper-state:pc03:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:pc03:eth1:rt01:eth2:
    dataRef: ping_loss_ratio:pc03:192.168.20.254
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  pc01:eth1:sw01:eth1:
    dataRef: oper-state:pc01:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:pc01:eth1:sw01:eth1:
    dataRef: sw01:eth1:in 
    label: *label-config 
    strokeColor: 
      thresholds: *thresholds-traffic 
  sw01:eth2:pc02:eth1:
    dataRef: oper-state:sw01:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:sw01:eth2:pc02:eth1:
    dataRef: sw01:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  sw01:eth3:rt01:eth1:
    dataRef: oper-state:sw01:eth3
    fillColor:
      thresholds: *thresholds-operstate
  link_id:sw01:eth3:rt01:eth1:
    dataRef: sw01:eth3:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rt01:eth1:sw01:eth3:
    dataRef: oper-state:rt01:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rt01:eth1:sw01:eth3:
    dataRef: rt01:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rt01:eth2:pc03:eth1:
    dataRef: oper-state:rt01:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rt01:eth2:pc03:eth1:
    dataRef: rt01:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
