---
anchors: # 再利用可能な設定の定義
  thresholds-operstate: &thresholds-operstate # インターフェースの状態によって色を決定
  - color: red
    level: 0
  - color: green
    level: 1
  thresholds-traffic: &thresholds-traffic # トラフィック量によって色を決定
  - color: gray 
    level: 0
  - color: green
    level: 49
  - color: yellow
    level: 250
  - color: orange
    level: 1000
  - color: red
    level: 4000 #4Mbps
  label-config: &label-config # リンクのラベル設定 xxxb/sと出力される
    separator: replace
    units: bps
    decimalPoints: 1
    valueMappings:
    - valueMax: 49
      text: ​
    - valueMin: 50
cellIdPreamble: cell-
cells:
  sw01:eth1:pc01:eth1: # ポートのID
    dataRef: oper-state:sw01:eth1 # データ参照
    fillColor: # 塗りつぶしの設定
      thresholds: *thresholds-operstate # インターフェースの状態によって色を決定
  link_id:sw01:eth1:pc01:eth1: # リンクのID
    dataRef: sw01:eth1:out # データ参照
    label: *label-config # ラベル設定
    strokeColor: # ストロークの色
      thresholds: *thresholds-traffic # トラフィック量によって色を決定
  pc02:eth1:sw01:eth2:
    dataRef: oper-state:pc02:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:pc02:eth1:sw01:eth2:
    dataRef: pc02:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  pc03:eth1:rt01:eth2:
    dataRef: oper-state:pc03:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:pc03:eth1:rt01:eth2:
    dataRef: pc03:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  pc01:eth1:sw01:eth1:
    dataRef: oper-state:pc01:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:pc01:eth1:sw01:eth1:
    dataRef: pc01:eth1:out 
    label: *label-config 
    strokeColor: 
      thresholds: *thresholds-traffic 
  sw01:eth2:pc02:eth1:
    dataRef: oper-state:sw01:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:sw01:eth2:pc02:eth1:
    dataRef: sw01:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  sw01:eth3:rt01:eth1:
    dataRef: oper-state:sw01:eth3
    fillColor:
      thresholds: *thresholds-operstate
  link_id:sw01:eth3:rt01:eth1:
    dataRef: sw01:eth3:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rt01:eth1:sw01:eth3:
    dataRef: oper-state:rt01:eth1
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rt01:eth1:sw01:eth3:
    dataRef: rt01:eth1:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  rt01:eth2:pc03:eth1:
    dataRef: oper-state:rt01:eth2
    fillColor:
      thresholds: *thresholds-operstate
  link_id:rt01:eth2:pc03:eth1:
    dataRef: rt01:eth2:out
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
