# グローバル設定
username: admin 
timeout: 30s

# 共通サブスクリプション設定
common_arista_subscriptions: &common_arista_subs #設定名：&エイリアス名
  skip-verify: true #安全な接続のための署名検証をスキップ
  insecure: true #TLSを使用しないgRPC接続を確立したい
  password: admin
  encoding: json_ietf #エンコーディング形式
  subscriptions: #サブスクリプションのリスト
    - cpu
    - mem
    - version_info
    - interface_state
    - interface_config
    - boot_time

# ターゲットデバイス設定
targets:
  sw01:6030: *common_arista_subs #ターゲット名:ポート番号:共通サブスクリプションのエイリアス名
  rt01:6030: *common_arista_subs

# サブスクリプションの詳細
subscriptions:

  ### General Information ###
  cpu:
    paths:
      - components/component/cpu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  mem:
    paths:
      - components/component/state/memory/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  version_info:
    paths:
      - system/state/software-version
    mode: stream
    stream-mode: sample
    sample-interval: 60s

  interface_state:
    paths:
      - interfaces/interface/state/counters
      - interfaces/interface/state/admin-status
      - interfaces/interface/state/oper-status
      - interfaces/interface/state/mtu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  interface_config:
    paths:
      - interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  boot_time:
    paths:
      - system/state/boot-time
    mode: stream
    stream-mode: sample
    sample-interval: 60s
  
# 出力設定
outputs:
  prom-output:
    type: prometheus
    listen: :9273
    append-subscription-name: true
    event-processors:
      - trim-prefixes
      - bounce-map
      - rename-interface
      - eos-version

# プロセッサ設定
processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  bounce-map:
    event-strings:
      value-names:
        - oper-status
        - admin-status
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
        - replace:
            apply-on: "value"
            old: "UP"
            new: "1"
        - replace:
            apply-on: "value"
            old: "DOWN"
            new: "0"
  rename-interface:
    event-strings:
      tag-names:
        - "^interface_name"
      transforms:
        - replace:
            apply-on: "value"
            old: "ethernet-(\\d+)/(\\d+)"
            new: "e$1-$2"
        - replace:
            apply-on: "value"
            old: "Ethernet(\\d+)"
            new: "eth$1"
  rename-source:
    event-strings:
      tag-names:
        - "^source"
      transforms:
        - replace:
            apply-on: "value"
            old: "(\\d+):(\\d+)"
            new: "$1"
  eos-version:
    event-strings:
      value-names:
        - ".*version$"
        - ".*arch$"
      transforms:
        - replace:
            apply-on: "value"
            old: "EOS"
            new: "eos"
