# グローバル設定
username: admin 
timeout: 30s

# 共通サブスクリプション設定
common_arista_subscriptions: &common_arista_subs #設定名：&エイリアス名
  skip-verify: true #安全な接続のための署名検証をスキップ
  insecure: true #TLSを使用しないgRPC接続を確立したい
  password: admin
  encoding: json_ietf #エンコーディング形式
  subscriptions: #サブスクリプションのリスト
    - eos_bgp_neighbors
    - eos_cpu
    - eos_cpu_load_avg
    - eos_mem
    - eos_int_counters
    - eos_int_admin_state
    - eos_int_oper_state
    - eos_int_config
    - eos_show_version
    - eos_boot_time
    - eos_hardware

# ターゲットデバイス設定
targets:
  sw01:6030: *common_arista_subs #ターゲット名:ポート番号:共通サブスクリプションのエイリアス名
  rt01:6030: *common_arista_subs

# サブスクリプションの詳細
subscriptions:
  eos_bgp_neighbors:
    paths: # メトリクス情報を取得するパス
      - /network-instances/network-instance[name=default]/protocols/protocol[name=BGP]/bgp/neighbors
    mode: stream # ストリームモード 他にONCE, POLLがある
    stream-mode: sample # サンプリングモード 他にON_CHANGE, TARGET_DEFINEDがある
    sample-interval: 5s # サンプリングの感覚

  eos_cpu:
    paths:
      - components/component/cpu
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_cpu_load_avg:
    paths:
      - eos_native:/Kernel/sysinfo
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_mem:
    paths:
      - components/component/state/memory/
      - system/memory/kernel/state
      - system/memory/state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_int_counters:
    paths:
      - /interfaces/interface[name=*]/state/counters
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_int_admin_state:
    paths:
      - /interfaces/interface[name=*]/state/admin-status
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_int_oper_state:
    paths:
      - /interfaces/interface[name=*]/state/oper-status
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_int_config:
    paths:
      - interfaces/interface/subinterfaces/subinterface/ipv4/addresses/address/config
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  eos_show_version:
    paths:
      - eos_native:/Eos/image
    mode: stream
    stream-mode: sample
    sample-interval: 60s

  eos_boot_time:
    paths:
      - system/state/boot-time
    mode: stream
    stream-mode: sample
    sample-interval: 60s

  eos_hardware:
    paths:
      - components/component/state
      - eos_native:/Sysdb/hardware/entmib
    mode: stream
    stream-mode: sample
    sample-interval: 60s

# 出力設定
outputs:
  prom: #出力設定名
    type: prometheus #prometheus形式(Pull型)
    listen: :9273 #listenするポート番号
    strings-as-labels: true #文字列をプロメテウスのラベルとして扱う
    export-timestamps: true #ターゲットから受信したタイムスタンプをエクスポートする
    debug: false
    event-processors: #メッセージを処理するプロセッサのリスト 
      - eos-version
      - trim-prefixes
      - bounce-map
      - rename-eos-interface
      - rename-source

# プロセッサ設定
processors:
  rename-eos-interface: #プロセッサ名
    event-strings: # stringに関するイベント
      tag-names: #タグ名
        - "^interface_name"
      transforms: #変換
        - replace: #Ethernetをethに変換
            apply-on: "value"
            old: "Ethernet(\\d+)"
            new: "eth$1"
  bounce-map:
    event-strings:
      value-names: #値名
        - oper-status
        - admin-status
      transforms:
        - replace: #UPを1に、DOWNを0に変換
            apply-on: "value"
            old: "UP"
            new: "1"
        - replace:
            apply-on: "value"
            old: "DOWN"
            new: "0"
  eos-version:
    event-strings:
      value-names:
        - ".*version$"
        - ".*arch$"
      transforms:
        - replace:
            apply-on: "value"
            old: "EOS"
            new: "eos"
  trim-prefixes:
    event-strings:
      value-names:
        - "^/state/.*"
      transforms:
        - trim-prefix:
            apply-on: "name"
            prefix: "/state/"
  rename-source:
    event-strings:
      tag-names:
        - "^source"
      transforms:
        - replace:
            apply-on: "value"
            old: "(\\d+):(\\d+)"
            new: "$1"
